# Generated by Django 5.1.1 on 2024-10-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=150)),
                ('course_category', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('course_price', models.CharField(max_length=150)),
                ('course_duration', models.CharField(max_length=150)),
                ('rating', models.CharField(max_length=150)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('learning_style', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=150)),
                ('course_level', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('surname', models.CharField(max_length=150)),
                ('age', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('interests', models.CharField(max_length=150)),
                ('grade', models.CharField(max_length=150)),
            ],
        ),
    ]
